language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install: "pip install assemblycoins; python setup.py install"
# command to run tests
script: cd assemblycoins/tests; py.test -vv
